org: andrezipfdev
app: nubank-to-splitwise
service: nubank-to-splitwise
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  nubank-to-splitwise:
    handler: index.run
    events:
      - schedule: rate(5 minutes)

plugins:
  - serverless-plugin-typescript
